class P2NumerosParesFibonacci(
    private val n: Int
){

    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
    the first 10 terms will be:
    1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.
     */

    private var soma = 0

    private var fibonacci = 1
    private var anterior = 0
    private var suporte = 0

    private var verificaCalculo = false

    fun calculaNumerosParesFibonacci(){
        while(true){

            suporte = fibonacci
            fibonacci += anterior
            anterior = suporte

            if(fibonacci % 2 == 0){
                soma += fibonacci
            }

            if(fibonacci > n){
                break
            }

        }
        verificaCalculo = true
    }

    fun mostraResultado():String{
        if(verificaCalculo){
            return "A soma dos numeros pares de fibonacci menores que $n é: $soma"
        }
        throw Exception("Realize o calculo primeiro")
    }

}